ALTER TABLE public.shoppings
  ADD COLUMN IF NOT EXISTS phone VARCHAR DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS address TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS commission_rate NUMERIC(5,4) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS withholds_pit BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS pit_rate NUMERIC(5,4) DEFAULT NULL;
