ALTER TABLE public.tour_shoppings
  ADD COLUMN IF NOT EXISTS withholds_pit BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS pit_rate NUMERIC(5,4) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS pit_amount NUMERIC DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS net_commission NUMERIC DEFAULT NULL;
